// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjuEWRoxctIhAPe0LJfYL64xA9trImh_Y',
    appId: '1:1058122216239:web:66f7b4e4e9c89728e2e7da',
    messagingSenderId: '1058122216239',
    projectId: 'rentalcar-31233',
    authDomain: 'rentalcar-31233.firebaseapp.com',
    storageBucket: 'rentalcar-31233.appspot.com',
    measurementId: 'G-RPKZ9EF49F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe3-FZA6htKZmD1A18JXHwqDIdS0hp1RY',
    appId: '1:1058122216239:android:94f72fd6458dbf42e2e7da',
    messagingSenderId: '1058122216239',
    projectId: 'rentalcar-31233',
    storageBucket: 'rentalcar-31233.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVbYJw6v3L05RjAZhWhM2zGtAGvzJmOM8',
    appId: '1:1058122216239:ios:3c917b833f10d305e2e7da',
    messagingSenderId: '1058122216239',
    projectId: 'rentalcar-31233',
    storageBucket: 'rentalcar-31233.appspot.com',
    iosBundleId: 'com.example.luxurycars',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVbYJw6v3L05RjAZhWhM2zGtAGvzJmOM8',
    appId: '1:1058122216239:ios:f7c46ab9c683f39de2e7da',
    messagingSenderId: '1058122216239',
    projectId: 'rentalcar-31233',
    storageBucket: 'rentalcar-31233.appspot.com',
    iosBundleId: 'com.example.luxurycars.RunnerTests',
  );
}
