// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6Zg9BA623l--21idrkgXOca2RLptwleg',
    appId: '1:84697927902:web:4f6a98831303cbd233324f',
    messagingSenderId: '84697927902',
    projectId: 'nothins-564df',
    authDomain: 'nothins-564df.firebaseapp.com',
    storageBucket: 'nothins-564df.appspot.com',
    measurementId: 'G-CE7Z03R709',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAHjuuBXfWvbdk3OwDW6tATtM2KlM0hqk',
    appId: '1:84697927902:android:c5f653008ad182e933324f',
    messagingSenderId: '84697927902',
    projectId: 'nothins-564df',
    storageBucket: 'nothins-564df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBP0LYx7s8pwZPp6ClbH1r5r4YFtN4vD8',
    appId: '1:84697927902:ios:acd28ac5d8df249f33324f',
    messagingSenderId: '84697927902',
    projectId: 'nothins-564df',
    storageBucket: 'nothins-564df.appspot.com',
    iosBundleId: 'com.example.luxurycars',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBP0LYx7s8pwZPp6ClbH1r5r4YFtN4vD8',
    appId: '1:84697927902:ios:65a60d10ee636dfc33324f',
    messagingSenderId: '84697927902',
    projectId: 'nothins-564df',
    storageBucket: 'nothins-564df.appspot.com',
    iosBundleId: 'com.example.luxurycars.RunnerTests',
  );
}
